

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReservationApplication.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BusReservationEntities : DbContext
{
    public BusReservationEntities()
        : base("name=BusReservationEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<BusDetails> BusDetails { get; set; }

    public virtual DbSet<ScheduleDetails> ScheduleDetails { get; set; }

    public virtual DbSet<UserDetail> UserDetail { get; set; }

    public virtual DbSet<BookingDetails> BookingDetails { get; set; }

}

}

